name: angular_dart_data_grid
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: aburagad <email@example.com>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  angular2: ^3.0.0
  angular_components: ^0.5.1
  polymer: 1.0.0-rc.19
  polymer_elements: 1.0.0-rc.10

dev_dependencies:
  angular_test: ^1.0.0-beta+2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0
  dart_sass_transformer: any

transformers:
- dart_sass_transformer
- angular2:
    entry_points: web/main.dart
- polymer:
    entry_points: web/index.html
- angular2/transform/reflection_remover:
    $include: test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
